// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {form} from '../models';
import {list} from '../models';
import {network} from '../models';

export function ExitWith252():Promise<void>;

export function ExitWithNumber(arg1:number):Promise<void>;

export function GetActiveMode():Promise<string>;

export function GetFormConfig():Promise<form.FormConfigResponse>;

export function GetListConfig():Promise<list.ListConfigResponse>;

export function GetSendRequest():Promise<network.GuiRequestForWebview>;

export function GetWindowInfo():Promise<network.WindowRequestForWebView>;

export function Greet(arg1:string):Promise<string>;

export function HandleSendRequest(arg1:network.GuiRequestForWebview):Promise<void>;

export function MinimizeGui():Promise<void>;

export function RunCmd(arg1:string):Promise<void>;

export function RunCmdAndExitForList(arg1:string,arg2:string,arg3:string,arg4:number,arg5:string):Promise<void>;

export function RunCmdForList(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RunReloadCmdForList(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SelectDir(arg1:string):Promise<string>;

export function SelectFile(arg1:string):Promise<string>;

export function WriteStderr(arg1:string):Promise<void>;

export function WriteStdout(arg1:string):Promise<void>;

export function WriteStdoutByHidden(arg1:string,arg2:number):Promise<void>;
