// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExitWith252() {
  return window['go']['main']['App']['ExitWith252']();
}

export function ExitWithNumber(arg1) {
  return window['go']['main']['App']['ExitWithNumber'](arg1);
}

export function GetActiveMode() {
  return window['go']['main']['App']['GetActiveMode']();
}

export function GetFormConfig() {
  return window['go']['main']['App']['GetFormConfig']();
}

export function GetListConfig() {
  return window['go']['main']['App']['GetListConfig']();
}

export function GetSendRequest() {
  return window['go']['main']['App']['GetSendRequest']();
}

export function GetWindowInfo() {
  return window['go']['main']['App']['GetWindowInfo']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HandleSendRequest(arg1) {
  return window['go']['main']['App']['HandleSendRequest'](arg1);
}

export function MinimizeGui() {
  return window['go']['main']['App']['MinimizeGui']();
}

export function RunCmd(arg1) {
  return window['go']['main']['App']['RunCmd'](arg1);
}

export function RunCmdAndExitForList(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['RunCmdAndExitForList'](arg1, arg2, arg3, arg4, arg5);
}

export function RunCmdForList(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunCmdForList'](arg1, arg2, arg3);
}

export function RunReloadCmdForList(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunReloadCmdForList'](arg1, arg2, arg3);
}

export function SelectDir(arg1) {
  return window['go']['main']['App']['SelectDir'](arg1);
}

export function SelectFile(arg1) {
  return window['go']['main']['App']['SelectFile'](arg1);
}

export function WriteStderr(arg1) {
  return window['go']['main']['App']['WriteStderr'](arg1);
}

export function WriteStdout(arg1) {
  return window['go']['main']['App']['WriteStdout'](arg1);
}

export function WriteStdoutByHidden(arg1, arg2) {
  return window['go']['main']['App']['WriteStdoutByHidden'](arg1, arg2);
}
